/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTransaksiRouteImport } from './routes/_authenticated/transaksi'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedLaporanRouteImport } from './routes/_authenticated/laporan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransaksiRoute = AuthenticatedTransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLaporanRoute = AuthenticatedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/transaksi': typeof AuthenticatedTransaksiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/laporan': typeof AuthenticatedLaporanRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/riwayat': typeof AuthenticatedRiwayatRoute
  '/transaksi': typeof AuthenticatedTransaksiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/laporan': typeof AuthenticatedLaporanRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRoute
  '/_authenticated/transaksi': typeof AuthenticatedTransaksiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/laporan'
    | '/menu'
    | '/riwayat'
    | '/transaksi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/laporan'
    | '/menu'
    | '/riwayat'
    | '/transaksi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/laporan'
    | '/_authenticated/menu'
    | '/_authenticated/riwayat'
    | '/_authenticated/transaksi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transaksi': {
      id: '/_authenticated/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof AuthenticatedTransaksiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/laporan': {
      id: '/_authenticated/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthenticatedLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLaporanRoute: typeof AuthenticatedLaporanRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRoute
  AuthenticatedTransaksiRoute: typeof AuthenticatedTransaksiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLaporanRoute: AuthenticatedLaporanRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRoute,
  AuthenticatedTransaksiRoute: AuthenticatedTransaksiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
